<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Lexikon\Specifications\" />
		<Folder Include="Media\Paper\" />
		<Folder Include="Media\Mag\" />
		<Folder Include="OLAP\Facts\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="CommunityToolkit.Diagnostics" />
		<PackageReference Include="CommunityToolkit.HighPerformance" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" />
		<PackageReference Include="Polly" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\WordWise.Framework\WordWise.Framework.csproj" />
	</ItemGroup>

</Project>
